name: "💡 Feature Request"
description: Create a new ticket for a new feature request
labels: [
  "enhancement"
]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: basic_example
    attributes:
      label: "Basic Examples"
      placeholder: A few specific examples about your feature request.
    validations:
      required: true
